export const Franchises = [
  {
    id: "01",
    name: "Franchises 1",
    area: "Area 1",
    details: "Franchises 1",
    creation_date: "15/03/2020",
  },
  {
    id: "02",
    name: "Franchises 2",
    area: "Area 2",
    details: "Franchises 2",
    creation_date: "15/03/2020",
  },
  {
    id: "03",
    name: "Franchises 3",
    area: "Area 3",
    details: "Franchises 3",
    creation_date: "15/03/2020",
  },
  {
    id: "04",
    name: "Franchises 4",
    area: "Area 4",
    details: "Franchises 4",
    creation_date: "15/03/2020",
  },
];

export const Packages = [
  {
    id: "01",
    name: "Packages 1",
    duration: "1 Month",
    charges: "Rs 2000",
    franchise: "Franchises 1",
    data: "2Mb",
    description: "Packages 1",
    picture: "",
    status: "true",
    creation_date: "15/03/2020",
  },
  {
    id: "02",
    name: "Packages 2",
    duration: "2 Month",
    charges: "Rs 3000",
    franchise: "Franchises 2",
    data: "3Mb",
    description: "Packages 2",
    picture: "",
    status: "true",
    creation_date: "15/03/2020",
  },
  {
    id: "03",
    name: "Packages 3",
    duration: "3 Month",
    charges: "Rs 4000",
    franchise: "Franchises 3",
    data: "4Mb",
    description: "Packages 3",
    picture: "",
    status: "true",
    creation_date: "15/03/2020",
  },
  {
    id: "04",
    name: "Packages 4",
    duration: "4 Month",
    charges: "Rs 5000",
    franchise: "Franchises1",
    data: "5Mb",
    description: "Packages 4",
    picture: "",
    status: "true",
    creation_date: "15/03/2020",
  },
];

export const types = [
  { id: "Monthly", name: "Monthly" },
  { id: "Weekly", name: "Weekly" },
  {
    id: "Daily",
    name: "Daily",
  },
];
